### ISSUE TITLE
QDialog moved by other supercontributors

### ISSUE THREAD

**Issue by telecran-telecrit** [vitperov/TtMapEditor#3]
```
C:\Users\User\Solutions\TtMapEditor2>python TerrainEditor.py
Traceback (most recent call last):
  File "TerrainEditor.py", line 8, in <module>
    from modules.Terrain.TerrainMapController import *
  File "C:\Users\User\Solutions\TtMapEditor2\modules\Terrain\TerrainMapController.py", line 13, in <module>
    from modules.Terrain.TerrainGeneratorSettingsDlg import *
  File "C:\Users\User\Solutions\TtMapEditor2\modules\Terrain\TerrainGeneratorSettingsDlg.py", line 20, in <module>
    class TerrainGeneratorSettingsDlg(QtGui.QDialog):
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QDialog'
```

**Comment by telecran-telecrit** [comment]
I will fix it. It is simple.
